### ISSUE TITLE
Unable to Load g_fitted.txt

### ISSUE THREAD

**Issue by therhetoricalcow** [uzh-rpg/active_camera_exposure_control#1]
Hi, I've initialized my setup as to how you've detailed but when I load the absolute path directory to my g_fitted,g_deriv,etc I keep running into "Could not open file /home/biorobotics/catkin_ws/src/blaser_mapping/pipe_blaser_ros/exposure_control/data/g_fitted.txt". This is for sure the path of my text file and I'm able to open it with fstream in my other scripts.

**Comment by therhetoricalcow** [comment]
Snippet of my	code
```
string photometric_calib_dir = "/home/avaneesh/catkin_ws/src/blaser_mapping/pipe_blaser_ros/exposure_control/data/grey_downsample_20";
	if(1)
	{
		auto_exposure::AutoCameraOptions options;
		options.ae_method = auto_exposure::AutoExposureMethod::kMeanIntensity;
		// load photometric model
		photometric_camera::PhotometricModel::Ptr photo_model = photometric_camera::PhotometricModel::loadModel(photometric_calib_dir);
		std::shared_ptr<auto_exposure::AutoCameraSettings> controller = std::make_shared<auto_exposure::AutoCameraSettings>(options, photo_model);
	}

```

**Comment by therhetoricalcow** [comment]
Nevermind resolved... saw that g_fitted, g', and g'' needed the 256 values from being fit instead of just the polynomial coeff

**Comment by gcioffi** [comment]
Issue seems solved
